spring.config.import=optional:file:./secrets.properties
spring.application.name=backend

# --- DATABASE CONFIG ---
spring.datasource.url=jdbc:postgresql://localhost:5432/cyberscale
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.continue-on-error=true

server.error.include-message=always
logging.level.org.springframework.security=DEBUG
spring.jackson.serialization.write-dates-as-timestamps=false

# --- CONFIG SIMULATION ---
cyberscale.simulation.attacker-ip=192.168.1.66

# --- CONFIG IA (Hugging Face) ---
ai.huggingface.api-url=https://router.huggingface.co/v1/chat/completions
ai.huggingface.api-key=${HF_API_KEY:}
ai.huggingface.model=HuggingFaceH4/zephyr-7b-beta:featherless-ai
ai.mock.enabled=false

# --- RABBITMQ CONFIG ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:user}
spring.rabbitmq.password=${RABBITMQ_PASS}

# Configuration imposée par le Ticket W-02
app.rabbitmq.exchange=cyberscale.events
app.rabbitmq.queue=queue.player.actions
app.rabbitmq.routingkey=player.action

app.rabbitmq.routingkey=player.action

app.rabbitmq.queue.infra=queue.infra.execution
app.rabbitmq.routingkey.infra=infra.execution