apiVersion: v1
kind: Pod
metadata:
  name: ${POD_NAME}
  labels:
    app: honeypot-mysql
    type: dynamic-trap
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "${RANDOM_PASS}"
        - name: MYSQL_DATABASE
          value: "users_db"
  restartPolicy: Never