apiVersion: v1
kind: Pod
metadata:
  name: ${POD_NAME}
  labels:
    app: honeypot-mysql
    type: dynamic-trap
spec:
  runtimeClassName: kata
  automountServiceAccountToken: false
  
  containers:
    - name: mysql
      image: mysql:5.7
      ports:
        - containerPort: 3306
      
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
          ephemeral-storage: "500Mi"
        limits:
          memory: "512Mi"
          cpu: "500m"
          ephemeral-storage: "1Gi"
          
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "${RANDOM_PASS}"
        - name: MYSQL_DATABASE
          value: "users_db"
  restartPolicy: Never